### ISSUE TITLE
Suggestion: functional api

### ISSUE THREAD

**Issue by mangecoeur** [SeTeM/pync#20]
Just a thought 

``` python
from pync import Notifier
Notifier.notify(...)
```

Seems a bit redundant. Why not have an api like

``` python
import pync
pync.notify(...)
```

Which internally would just do

``` python
def notify(*args, **kwargs):
    Notifier.notify(*args, **kwargs)
```

**Comment by SeTeM** [comment]
Great idea! Can you make PR for this? It is also important not to break api for previous versions

**Comment by maxkrivich** [comment]
implemented in this commit: https://github.com/SeTeM/pync/commit/adf3d3d65c0bc5e3f3fea58ac3664dfab1c0dd81
