### ISSUE TITLE
Doesn't work if the message begins with square bracket ("[")

### ISSUE THREAD

**Issue by bbbbbbbbba** [SeTeM/pync#30]
`Notifier.notify('[')` fails silently. `Notifier.notify('.[')` works correctly.

**Comment by maxkrivich** [comment]
@bbbbbbbbba looks like it's problem with `terminal-notifier`

**Comment by maxkrivich** [comment]
@bbbbbbbbba use escape character to fix this problem. 
```python
>>> import pync
>>> pync.notify('\[')
```

**Comment by bbbbbbbbba** [comment]
I don't think the package should let the user do the escaping, unless the unescaped bracket has a useful and documented function. Is that the case here?

**Comment by maxkrivich** [comment]
@bbbbbbbbba it's simple wrapper without extra logic, but you're right about that. Can you make PR for this?
