### ISSUE TITLE
Failure on High Sierra

### ISSUE THREAD

**Issue by BarrySmith** [SeTeM/pync#32]
$ python
Python 2.7.10 (default, Jul 15 2017, 17:16:57) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```python
>>> from pync import Notifier
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.13-intel/egg/pync/__init__.py", line 3, in <module>
  File "build/bdist.macosx-10.13-intel/egg/pync/TerminalNotifier.py", line 130, in <module>
  File "build/bdist.macosx-10.13-intel/egg/pync/TerminalNotifier.py", line 37, in __init__
Exception: pync was not properly installed. Head over to https://github.com/SeTeM/pync/ and file a bug.```

**Comment by shadow-identity** [comment]
Hi @BarrySmith

In my pull request #33 I supposed to update Terminal Notifier to version 2.0.0
You can get `pync` with updated Terminal Notifier in my forked repository.
Updating Terminal Notifier to version 2 resolved my problems with pync. With my High Sierra and Python 3 it works fine. I think Python 2 should works too.
I'll be glad to receive feedback from you.

**Comment by shadow-identity** [comment]
@BarrySmith, you can try out 2.0.0 from pypi

**Comment by maxkrivich** [comment]
@BarrySmith please give feedback if everything is alright.
