### ISSUE TITLE
remove_notifications and list_notifications are not promoted to package level

### ISSUE THREAD

**Issue by andysim3d** [SeTeM/pync#45]
**Describe the bug**
can not call
`pync.remove_notifications(os.getpid())` and `pync.list_notifications(os.getpid())` directly because those two function are not promote to package level.

**To Reproduce**
In any python file, call `pync.remove_notifications(os.getpid())` or 
`pync.list_notifications(os.getpid())`, it will raise execption `module 'pync' has no attribute 'remove_notifications'`

**Expected behavior**
As document said, it supports `pync.remove_notifications` and `pync.list_notification`

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 10.14.4

**Additional context**

**Comment by teamhide** [comment]
Same issue here
